### ISSUE TITLE
存档无法显示所有文章

### ISSUE THREAD

**Issue by navono** [gaoryrt/hexo-theme-pln#22]
当文章数超过一页后，存档界面只显示了第一页的文章，第二页就没有显示了。
比如
tag为CPP的http://codingwith.me/tags/CPP/   这里显示了二月份的。
tag为archive的http://codingwith.me/archives/   显示到三月份就没了。

有谁碰到过相似的问题吗？

**Comment by gaoryrt** [comment]
我的锅，这是因为你的主设置里面设置了archive分页长度
在 `HEXO_DIR/_config.yml` 里面：
```
archive_generator:
  per_page: 0
  yearly: true
  monthly: true
```

这个per_page 改成0 就行

看有空来重写这个主题，自己水平进步了，发现可以优化的地方很多
